
name: SimpleChat Docker Image Publish (nadoyle branch)

on:
  push:
    branches:
    - nadoyle
    - azureBillingPlugin

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v2
      with:
        # Container registry username
        username: ${{ secrets.ACR_USERNAME_NADOYLE }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD_NADOYLE }}
        # Container registry server url
        login-server: ${{ secrets.ACR_LOGIN_SERVER_NADOYLE }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:         
        docker build . --file application/single_app/Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER_NADOYLE }}/simple-chat-dev:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ${{ secrets.ACR_LOGIN_SERVER_NADOYLE }}/simple-chat-dev:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ${{ secrets.ACR_LOGIN_SERVER_NADOYLE }}/simple-chat-dev:latest;
        docker push ${{ secrets.ACR_LOGIN_SERVER_NADOYLE }}/simple-chat-dev:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ${{ secrets.ACR_LOGIN_SERVER_NADOYLE }}/simple-chat-dev:latest;
